# See https://github.com/dart-lang/mono_repo for details
stages:
  - analyze_and_format:
    - group:
        - dartfmt: sdk
        - dartanalyzer: --fatal-warnings .
      dart:
        - dev
    - group:
        - dartanalyzer: --fatal-warnings .
      dart:
        - 2.3.0-dev.0.1

cache:
  directories:
  - .dart_tool/build
