# See https://github.com/dart-lang/mono_repo for details
dart:
  - stable

stages:
  - analyze_and_format:
    - dartfmt
    - dartanalyzer: --fatal-warnings .
  - unit_test:
    - test

cache:
  directories:
  - .dart_tool/build