# See https://github.com/dart-lang/mono_repo for details
dart:
  - stable

stages:
  - analyzer_and_format:
    - dartfmt
    - dartanalyzer: --fatal-infos --fatal-warnings .

cache:
  directories:
  - .dart_tool/build