# See https://github.com/dart-lang/mono_repo for details
dart:
  - dev

stages:
  - analyze_and_format:
    - group:
      - dartfmt
      - dartanalyzer: --fatal-warnings .
  - unit_test:
    - group:
      - command: ./tool/travis/install_protoc.sh
      - test: --run-skipped

cache:
  directories:
  - .dart_tool/build
