# See https://github.com/google/mono_repo.dart for details
dart:
  - dev

stages:
  - analyze_and_format_core:
    - group:
        - dartfmt: sdk
        - dartanalyzer: --fatal-warnings .
      dart:
        - dev
  - unit_test:
    - group:
      - command: ./tool/travis/install_protoc.sh
      - test: --run-skipped

cache:
  directories:
  - .dart_tool
