name: material_tab_example
publish_to: none

environment:
  sdk: '>=2.10.5 <3.0.0'

dependencies:
  angular: ^7.0.0
  angular_components: ^1.0.0
  angular_gallery:
    path: ../../angular_gallery
  angular_gallery_section:
    path: ../../angular_gallery_section
  build_config: ^1.0.0

dependency_overrides:
  angular_components:
    path: ../../angular_components
