name: material_stepper_example
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=2.1.0-dev.9.4 <3.0.0'
dependencies:
  angular: ^5.2.0
  angular_components: 0.12.0
  angular_gallery_section:
    path: ../../angular_gallery_section
  build_config: '>=0.2.6 <0.4.0'
