targets:
  $default:
    builders:
      angular_components|scss_builder:
        enabled: True
      angular|angular:
        generate_for:
          exclude: ["lib/**"]

builders:
  angular_gallery:
    target: ":angular_gallery"
    import: "package:angular_gallery/builders.dart"
    builder_factories: [
      galleryAppBuilder,
      galleryLibBuilder,
      syntaxHighlightBuilder,
    ]
    build_extensions: {
      ".html": [".dart"],
      "$web$": ["index.html", "main.dart", "style.scss"]}
    auto_apply: dependents
    runs_before: ["angular|angular", "angular_components|scss_builder"]
