# See https://github.com/google/mono_repo.dart for details
stages:
  - analyze_and_format_core:
    - group:
        - dartfmt: sdk
        - dartanalyzer: --fatal-infos .
      dart:
        - dev
    - group:
        - dartanalyzer: .
      dart:
        - 2.10.5

cache:
  directories:
  - .dart_tool
