name: app_layout_example
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=2.0.0-dev.69.5 <3.0.0'
dependencies:
  angular: ^5.0.0
  angular_components: 0.9.2
  angular_gallery_section:
    path: ../../angular_gallery_section
  build_config: '>=0.2.6 <0.4.0'
