# See https://github.com/google/mono_repo.dart for details
stages:
  - analyze_and_format_examples_1:
    - group:
        - format
        - analyze: --fatal-infos .
      dart:
        - dev
    - group:
        - analyze: .
      dart:
        - 2.14.2

cache:
  directories:
  - .dart_tool
