# See https://github.com/dart-lang/mono_repo for details
dart:
  - 2.5.0-dev.1.0
  - dev

stages:
  - build:
    - group:
      - command: pub run build_runner build web
      - command: pub run build_runner build web --release

cache:
  directories:
    - .dart_tool/build
