# See https://github.com/google/mono_repo.dart for details
dart:
  - 2.10.5
  - dev

stages:
  - build:
    - group:
      - command: pub run build_runner build web
      - command: pub run build_runner build web --release

cache:
  directories:
    - .dart_tool
