name: angular_components_example
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=2.5.0-dev.1.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha+1
  angular_components: 0.14.0-alpha+1
  angular_gallery:
    path: ../../angular_gallery
  app_layout_example:
    path: ../app_layout_example
  build_config: '>=0.2.6 <0.5.0'
  material_button_example:
    path: ../material_button_example
  material_card_example:
    path: ../material_card_example
  material_checkbox_example:
    path: ../material_checkbox_example
  material_chips_example:
    path: ../material_chips_example
  material_datepicker_example:
    path: ../material_datepicker_example
  material_dialog_example:
    path: ../material_dialog_example
  material_expansionpanel_example:
    path: ../material_expansionpanel_example
  material_icon_example:
    path: ../material_icon_example
  material_input_example:
    path: ../material_input_example
  material_list_example:
    path: ../material_list_example
  material_menu_example:
    path: ../material_menu_example
  material_popup_example:
    path: ../material_popup_example
  material_progress_example:
    path: ../material_progress_example
  material_radio_example:
    path: ../material_radio_example
  material_select_example:
    path: ../material_select_example
  material_slider_example:
    path: ../material_slider_example
  material_spinner_example:
    path: ../material_spinner_example
  material_stepper_example:
    path: ../material_stepper_example
  material_tab_example:
    path: ../material_tab_example
  material_toggle_example:
    path: ../material_toggle_example
  material_tooltip_example:
    path: ../material_tooltip_example
  material_tree_example:
    path: ../material_tree_example
  material_yes_no_buttons_example:
    path: ../material_yes_no_buttons_example
  simple_html_example:
    path: ../simple_html_example
  scorecard_example:
    path: ../scorecard_example

dev_dependencies:
  build_runner: '>=0.10.0 <2.0.0'
  build_web_compilers: '>=0.4.0 <3.0.0'

dependency_overrides:
  angular_components:
    path: ../../angular_components
