name: simple_html_example
author: Dart Team <misc@dartlang.org>
environment:
  sdk: '>=2.2.1-dev.3.0 <3.0.0'
dependencies:
  angular: ^5.3.0
  angular_components: 0.13.0
  angular_gallery:
    path: ../../angular_gallery
  angular_gallery_section:
    path: ../../angular_gallery_section
  build_config: '>=0.2.6 <0.4.0'
  intl: '>=0.14.0 <0.17.0'
